### ISSUE TITLE
3D voxel painter for animation

### ISSUE THREAD

**Issue by freealise** [jel-app/smoothvoxels#5]
Hello,
I've made a 3d painting interface for Smooth Voxels (with morph targets already and skeleton also planned) in order to make animated videos, but don't think I'm going to maintain it as I keep getting other ideas.
Would you be interested?

![Screenshot 2023-10-10 at 08 32 48](https://github.com/webspace-sdk/smoothvoxels/assets/5275747/6024f561-e267-4595-9459-138045418b0e)
@gfodor

**Comment by gfodor** [comment]
Hey freealise, sorry I missed this, but appreciate the message. You might want to contact the smooth voxels author since he may be interested in such a tool!

**Comment by gfodor** [comment]
https://svox.glitch.me/

**Comment by freealise** [comment]
Thanks for your answer! I did contact him and he's interested in general, but not at present.

**Comment by gfodor** [comment]
ah great. Will re-close, and thanks again!
